import type { Capsule } from '../shared/types';

/**
 * Constructs the unified context restoration prompt to be injected into the new chat.
 */
export function buildRestorationPrompt(capsule: Capsule): string {
  const decisions = capsule.important_decisions.map(d => `- ${d}`).join('\n');
  const tasks = capsule.unresolved_tasks.map(t => `- [ ] ${t.text}`).join('\n');
  
  const uniqueFiles: string[] = [];
  if (capsule.messages) {
    capsule.messages.forEach(m => {
      if (m.files) {
        m.files.forEach(f => {
          if (!uniqueFiles.includes(f)) {
            uniqueFiles.push(f);
          }
        });
      }
    });
  }

  let filesStr = '';
  if (uniqueFiles.length > 0) {
    filesStr = `\n\n## Staged/Uploaded Files in the Previous Session:\n[IMPORTANT: The target AI cannot access the original binary contents of these files directly. User, please re-upload these files to this new chat tab if the AI needs to read their contents]:\n${
      uniqueFiles.map(f => `- ${f}`).join('\n')
    }`;
  }

  let transcriptStr = '';
  if (capsule.messages && capsule.messages.length > 0) {
    transcriptStr = `\n\n## Chat Transcript & Code History:\n${
      capsule.messages.map(m => `### ${m.role === 'user' ? 'User' : 'Assistant'}:\n${m.content}`).join('\n\n')
    }`;
  }

  return `[SYSTEM CONTEXT RESTORED - CARRYAI]
You are continuing a coding/work session from a previous AI chat thread. Please absorb this context capsule to resume the work seamlessly.

## Project Summary:
${capsule.summary}

## Current Goal:
${capsule.current_goal}

## Key Decisions & Stack:
${decisions || '- None recorded'}

## User Preferences & Style:
- Coding Style: ${capsule.user_preferences.coding_style || 'Not specified'}
- Tone: ${capsule.user_preferences.tone || 'Not specified'}
${capsule.user_preferences.custom_notes ? `- Additional Preferences: ${capsule.user_preferences.custom_notes}` : ''}

## Technologies / Entities:
${capsule.entities.join(', ') || 'None'}

## Unresolved Tasks (Next Steps):
${tasks || '- None recorded'}${filesStr}${transcriptStr}

---
Please acknowledge receipt of this context, referencing the provided transcript/code history and files checklist to resume the session. Briefly state the current goal and suggest immediate next steps. Let's proceed.`;
}

/**
 * Formats a capsule into a readable markdown report
 */
export function formatCapsuleToMarkdown(capsule: Capsule): string {
  const decisions = capsule.important_decisions.map(d => `- ${d}`).join('\n');
  const tasks = capsule.unresolved_tasks.map(t => `- [${t.completed ? 'x' : ' '}] ${t.text}`).join('\n');
  const entities = capsule.entities.map(e => `\`${e}\``).join(', ');

  let transcriptStr = '';
  if (capsule.messages && capsule.messages.length > 0) {
    transcriptStr = `

## Scraped Conversation Transcript

${capsule.messages.map(m => `### ${m.role === 'user' ? 'User' : 'AI Assistant'}\n${m.content}`).join('\n\n')}`;
  }

  return `# CarryAI Capsule: ${capsule.title}
 
* **Original Platform**: ${capsule.platform.toUpperCase()}
* **Created At**: ${new Date(capsule.created_at).toLocaleString()}
* **Source URL**: [Link](${capsule.url})
 
## Executive Summary
${capsule.summary}
 
## Active Objective
**Current Goal**: ${capsule.current_goal}
 
## Key Decisions & Stack
${decisions || '*No decisions recorded*'}
 
## Stack & Entities
${entities || '*No entities recorded*'}
 
## User Preferences
* **Coding Style**: ${capsule.user_preferences.coding_style}
* **Tone**: ${capsule.user_preferences.tone}
${capsule.user_preferences.custom_notes ? `* **Notes**: ${capsule.user_preferences.custom_notes}` : ''}
 
## Unresolved Tasks
${tasks || '*No tasks recorded*'}${transcriptStr}
 
---
*Generated by CarryAI. Import this capsule to resume your work session.*
`;
}

function escapeHtml(text: string): string {
  if (!text) return '';
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Formats a capsule into a beautiful offline-readable HTML document mirroring a chat application.
 */
export function formatCapsuleToHtml(capsule: Capsule): string {
  const decisions = capsule.important_decisions.map(d => `<li>${escapeHtml(d)}</li>`).join('\n');
  const tasks = capsule.unresolved_tasks.map(t => `<li><input type="checkbox" ${t.completed ? 'checked' : ''} disabled /> <span>${escapeHtml(t.text)}</span></li>`).join('\n');
  const entities = capsule.entities.map(e => `<span class="tag">${escapeHtml(e)}</span>`).join(' ');
  const prompt = buildRestorationPrompt(capsule);

  const messagesHtml = capsule.messages ? capsule.messages.map(m => {
    const roleClass = m.role === 'user' ? 'user' : 'assistant';
    const roleLabel = m.role === 'user' ? 'User' : (capsule.platform ? capsule.platform.toUpperCase() : 'AI Assistant');
    return `
      <div class="message-turn ${roleClass}">
        <div class="message-sender">${roleLabel}</div>
        <div class="message-bubble">${escapeHtml(m.content).replace(/\n/g, '<br>')}</div>
      </div>
    `;
  }).join('\n') : '<p class="no-messages">No chat history turns scraped.</p>';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CarryAI Conversation Export - ${escapeHtml(capsule.title)}</title>
  <style>
    :root {
      --bg: #f4f5f9;
      --card: #ffffff;
      --border: #d8dce8;
      --t1: #0d1117;
      --t2: #4a5568;
      --t3: #8a9bb5;
      --cyan: #0078d4;
      --cyan-light: rgba(0, 120, 212, 0.08);
      --green: #16a34a;
      --green-light: rgba(22, 163, 74, 0.08);
    }
    @media (prefers-color-scheme: dark) {
      :root {
        --bg: #0d1117;
        --card: #161b22;
        --border: #30363d;
        --t1: #c9d1d9;
        --t2: #8b949e;
        --t3: #6e7681;
        --cyan: #58a6ff;
        --cyan-light: rgba(88, 166, 255, 0.15);
        --green: #3fb950;
        --green-light: rgba(63, 185, 80, 0.15);
      }
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      background-color: var(--bg);
      color: var(--t1);
      display: flex;
      height: 100vh;
      overflow: hidden;
    }
    .sidebar {
      width: 320px;
      background: var(--card);
      border-right: 1px solid var(--border);
      display: flex;
      flex-direction: column;
      padding: 24px;
      overflow-y: auto;
      flex-shrink: 0;
    }
    .main-content {
      flex: 1;
      display: flex;
      flex-direction: column;
      background: var(--bg);
      overflow: hidden;
    }
    .header {
      padding: 20px 32px;
      background: var(--card);
      border-bottom: 1px solid var(--border);
      display: flex;
      justify-content: space-between;
      align-items: center;
      flex-shrink: 0;
    }
    .header h1 {
      font-size: 18px;
      font-weight: 700;
      letter-spacing: -0.3px;
    }
    .chat-container {
      flex: 1;
      padding: 32px;
      overflow-y: auto;
      display: flex;
      flex-direction: column;
      gap: 24px;
    }
    .message-turn {
      display: flex;
      flex-direction: column;
      max-width: 75%;
    }
    .message-turn.user {
      align-self: flex-end;
      align-items: flex-end;
    }
    .message-turn.assistant {
      align-self: flex-start;
      align-items: flex-start;
    }
    .message-sender {
      font-size: 11px;
      font-weight: 600;
      color: var(--t3);
      margin-bottom: 4px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .message-bubble {
      padding: 12px 16px;
      border-radius: 14px;
      font-size: 14px;
      line-height: 1.5;
      white-space: pre-wrap;
      word-break: break-word;
    }
    .user .message-bubble {
      background-color: var(--cyan);
      color: #ffffff;
      border-bottom-right-radius: 2px;
    }
    .assistant .message-bubble {
      background-color: var(--card);
      color: var(--t1);
      border: 1px solid var(--border);
      border-bottom-left-radius: 2px;
    }
    .logo-container {
      display: flex;
      align-items: center;
      gap: 10px;
      margin-bottom: 24px;
    }
    .logo {
      font-size: 24px;
    }
    .logo-text {
      font-size: 16px;
      font-weight: 800;
    }
    .section-title {
      font-size: 10px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 1px;
      color: var(--t3);
      margin-top: 20px;
      margin-bottom: 8px;
    }
    .section-body {
      font-size: 13px;
      color: var(--t2);
      line-height: 1.5;
    }
    .tag {
      display: inline-block;
      font-size: 11px;
      background: var(--bg);
      border: 1px solid var(--border);
      padding: 2px 8px;
      border-radius: 12px;
      margin-right: 4px;
      margin-bottom: 4px;
      font-weight: 500;
    }
    ul {
      list-style-type: none;
      padding-left: 0;
    }
    li {
      margin-bottom: 6px;
      display: flex;
      align-items: flex-start;
      gap: 6px;
    }
    li input {
      margin-top: 4px;
    }
    .btn {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      padding: 10px 16px;
      background: var(--cyan);
      color: #ffffff;
      border: none;
      border-radius: 8px;
      font-size: 13px;
      font-weight: 600;
      cursor: pointer;
      width: 100%;
      text-align: center;
      transition: opacity 0.15s ease;
    }
    .btn:hover { opacity: 0.9; }
    .no-messages {
      text-align: center;
      color: var(--t3);
      font-size: 14px;
      margin-top: 40px;
    }
    @media (max-width: 768px) {
      body { flex-direction: column; }
      .sidebar { width: 100%; height: 300px; border-right: none; border-bottom: 1px solid var(--border); }
      .chat-container { padding: 16px; }
      .message-turn { max-width: 90%; }
    }
  </style>
</head>
<body>
  <div class="sidebar">
    <div class="logo-container">
      <span class="logo">🧳</span>
      <span class="logo-text">CarryAI Export</span>
    </div>
    
    <button class="btn" id="copyBtn">Copy Context Prompt</button>
    
    <div class="section-title">Original Platform</div>
    <div class="section-body" style="text-transform: capitalize;">${escapeHtml(capsule.platform)}</div>
    
    <div class="section-title">Created At</div>
    <div class="section-body">${new Date(capsule.created_at).toLocaleString()}</div>
 
    <div class="section-title">Project Summary</div>
    <div class="section-body">${escapeHtml(capsule.summary)}</div>
 
    <div class="section-title">Current Goal</div>
    <div class="section-body">${escapeHtml(capsule.current_goal)}</div>
 
    ${decisions ? `<div class="section-title">Key Decisions</div><ul class="section-body">${decisions}</ul>` : ''}
    
    ${entities ? `<div class="section-title">Stack & Entities</div><div class="section-body" style="margin-top: 4px;">${entities}</div>` : ''}
 
    ${tasks ? `<div class="section-title">Unresolved Tasks</div><ul class="section-body">${tasks}</ul>` : ''}
  </div>
  <div class="main-content">
    <div class="header">
      <h1>${escapeHtml(capsule.title)}</h1>
    </div>
    <div class="chat-container">
      ${messagesHtml}
    </div>
  </div>
 
  <textarea id="promptData" style="display:none;">${escapeHtml(prompt)}</textarea>
 
  <script>
    document.getElementById('copyBtn').addEventListener('click', () => {
      const text = document.getElementById('promptData').value;
      navigator.clipboard.writeText(text).then(() => {
        const btn = document.getElementById('copyBtn');
        const oldText = btn.textContent;
        btn.textContent = 'Copied!';
        btn.style.backgroundColor = 'var(--green)';
        setTimeout(() => {
          btn.textContent = oldText;
          btn.style.backgroundColor = 'var(--cyan)';
        }, 2000);
      }).catch(err => {
        console.error('Failed to copy', err);
      });
    });
  </script>
</body>
</html>
`;
}
 
/**
 * Triggers a browser download file download
 */
export function triggerCapsuleDownload(capsule: Capsule, format: 'capsule' | 'json' | 'markdown' | 'html'): void {
  let content = '';
  let filename = `${capsule.title.toLowerCase().replace(/[^a-z0-9]+/g, '_')}`;
  let mimeType = 'application/json';
 
  if (format === 'markdown') {
    content = formatCapsuleToMarkdown(capsule);
    filename += '.md';
    mimeType = 'text/markdown';
  } else if (format === 'capsule') {
    content = JSON.stringify(capsule, null, 2);
    filename += '.capsule';
    mimeType = 'application/json';
  } else if (format === 'html') {
    content = formatCapsuleToHtml(capsule);
    filename += '.html';
    mimeType = 'text/html';
  } else {
    content = JSON.stringify(capsule, null, 2);
    filename += '.json';
    mimeType = 'application/json';
  }

  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  
  // Clean up
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
