import type { Capsule } from '../shared/types';

/**
 * Constructs the unified context restoration prompt to be injected into the new chat.
 */
export function buildRestorationPrompt(capsule: Capsule): string {
  const decisions = capsule.important_decisions.map(d => `- ${d}`).join('\n');
  const tasks = capsule.unresolved_tasks.map(t => `- [ ] ${t.text}`).join('\n');
  
  return `[SYSTEM CONTEXT RESTORED - CARRYAI]
You are continuing a coding/work session from a previous AI chat thread. Please absorb this context capsule to resume the work seamlessly.

## Project Summary:
${capsule.summary}

## Current Goal:
${capsule.current_goal}

## Key Decisions & Stack:
${decisions || '- None recorded'}

## User Preferences & Style:
- Coding Style: ${capsule.user_preferences.coding_style || 'Not specified'}
- Tone: ${capsule.user_preferences.tone || 'Not specified'}
${capsule.user_preferences.custom_notes ? `- Additional Preferences: ${capsule.user_preferences.custom_notes}` : ''}

## Technologies / Entities:
${capsule.entities.join(', ') || 'None'}

## Unresolved Tasks (Next Steps):
${tasks || '- None recorded'}

---
Please acknowledge receipt of this context. Briefly state the current goal and suggest the immediate next steps to continue. Keep your response brief. Let's proceed.`;
}

/**
 * Formats a capsule into a readable markdown report
 */
export function formatCapsuleToMarkdown(capsule: Capsule): string {
  const decisions = capsule.important_decisions.map(d => `- ${d}`).join('\n');
  const tasks = capsule.unresolved_tasks.map(t => `- [${t.completed ? 'x' : ' '}] ${t.text}`).join('\n');
  const entities = capsule.entities.map(e => `\`${e}\``).join(', ');

  let transcriptStr = '';
  if (capsule.messages && capsule.messages.length > 0) {
    transcriptStr = `

## Scraped Conversation Transcript

${capsule.messages.map(m => `### ${m.role === 'user' ? 'User' : 'AI Assistant'}\n${m.content}`).join('\n\n')}`;
  }

  return `# CarryAI Capsule: ${capsule.title}

* **Original Platform**: ${capsule.platform.toUpperCase()}
* **Created At**: ${new Date(capsule.created_at).toLocaleString()}
* **Source URL**: [Link](${capsule.url})

## Executive Summary
${capsule.summary}

## Active Objective
**Current Goal**: ${capsule.current_goal}

## Key Decisions & Stack
${decisions || '*No decisions recorded*'}

## Stack & Entities
${entities || '*No entities recorded*'}

## User Preferences
* **Coding Style**: ${capsule.user_preferences.coding_style}
* **Tone**: ${capsule.user_preferences.tone}
${capsule.user_preferences.custom_notes ? `* **Notes**: ${capsule.user_preferences.custom_notes}` : ''}

## Unresolved Tasks
${tasks || '*No tasks recorded*'}${transcriptStr}

---
*Generated by CarryAI. Import this capsule to resume your work session.*
`;
}

/**
 * Triggers a browser download file download
 */
export function triggerCapsuleDownload(capsule: Capsule, format: 'capsule' | 'json' | 'markdown'): void {
  let content = '';
  let filename = `${capsule.title.toLowerCase().replace(/[^a-z0-9]+/g, '_')}`;
  let mimeType = 'application/json';

  if (format === 'markdown') {
    content = formatCapsuleToMarkdown(capsule);
    filename += '.md';
    mimeType = 'text/markdown';
  } else if (format === 'capsule') {
    content = JSON.stringify(capsule, null, 2);
    filename += '.capsule';
    mimeType = 'application/json';
  } else {
    content = JSON.stringify(capsule, null, 2);
    filename += '.json';
    mimeType = 'application/json';
  }

  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  
  // Clean up
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
